package com.devtrack.repository;

import com.devtrack.model.Task;
import com.devtrack.model.TaskPriority;
import com.devtrack.model.TaskStatus;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.test.context.TestPropertySource;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Integration test for the persistence layer (task 9.1).
 *
 * <p>Feature: devtrack-task-management — the design's "Integration test (persistence wiring)"
 * section. Unlike the {@code TaskService} property tests (which run against an in-memory fake
 * repository to verify <em>our</em> business logic), this test drives the <strong>real</strong>
 * Spring Data JPA / Hibernate stack to confirm the infrastructure wiring itself: that a
 * {@link Task} entity actually maps to a table, persists, and reads back, and that the
 * {@link TaskRepository#findAllByOrderByIdAsc()} derived query returns rows in ascending-id order
 * end to end. It is intentionally small — a few representative cases, not a property test.
 *
 * <p><strong>Why {@code @DataJpaTest}?</strong> This slice annotation boots only the JPA layer
 * (entity manager, Hibernate, the Spring Data repositories) instead of the whole application
 * context, so the test is focused and fast. It also wraps each test method in a transaction that is
 * <em>rolled back</em> at the end, so tests never leave data behind and cannot interfere with each
 * other.
 *
 * <p><strong>Why H2 instead of MySQL?</strong> By convention {@code @DataJpaTest} replaces the
 * app's configured datasource (MySQL, see {@code application.properties}) with an embedded in-memory
 * database so the suite needs no external database server. We add H2 (test scope) to fill that role.
 * The {@link Task} entity uses only portable JPA features — {@code IDENTITY} id generation, plain
 * {@code VARCHAR} columns, and enums persisted by name — so H2 exercises the same mapping the app
 * relies on against MySQL. The {@code @TestPropertySource} below overrides the MySQL-specific
 * dialect/driver from {@code application.properties} so Hibernate targets H2 during the test.
 *
 * <p><strong>Note on {@code flush()}.</strong> Hibernate batches SQL and may not send an
 * {@code INSERT} to the database until it has to. Because the entity id is generated by the database
 * ({@code GenerationType.IDENTITY}), {@code save} triggers the insert and populates the id
 * immediately; {@code flush()} is called explicitly where we want to be certain the write reached
 * the database before we read it back.
 *
 * <p><strong>Validates: Requirements 8.6, 2.1</strong>
 */
@DataJpaTest
@TestPropertySource(properties = {
        // Point the JPA layer at an in-memory H2 database for this test, overriding the MySQL
        // datasource/dialect declared in application.properties.
        "spring.datasource.url=jdbc:h2:mem:devtrack-test;DB_CLOSE_DELAY=-1",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.datasource.username=sa",
        "spring.datasource.password=",
        // Clear the MySQL dialect from application.properties; Hibernate auto-detects H2's dialect
        // from the connection, so we deliberately do not set one here.
        "spring.jpa.properties.hibernate.dialect=",
        // Let Hibernate create the schema from the entities for the test run.
        "spring.jpa.hibernate.ddl-auto=create-drop"
})
class TaskRepositoryDataJpaTest {

    /**
     * The repository under test. Spring Data supplies the generated implementation; we are checking
     * that its {@code save}/{@code findById}/{@code findAllByOrderByIdAsc} operations actually work
     * against a live JPA layer.
     */
    @Autowired
    private TaskRepository taskRepository;

    // =====================================================================
    // 1. Persist and read back a single task (Requirement 8.6)
    // =====================================================================

    @Test
    @DisplayName("save persists a task and findById reads back the same field values (Req 8.6)")
    void savePersistsAndFindByIdReadsBack() {
        Task task = newTask("Write the design doc", "cover the API contract",
                TaskStatus.IN_PROGRESS, TaskPriority.HIGH);

        // Persist. With IDENTITY generation the database assigns the id during the insert.
        Task saved = taskRepository.save(task);
        taskRepository.flush();

        assertThat(saved.getId()).as("database should assign a non-null id on insert").isNotNull();

        // Read the row back by its assigned id and confirm every field survived the round trip.
        Task found = taskRepository.findById(saved.getId()).orElseThrow();

        assertThat(found.getId()).isEqualTo(saved.getId());
        assertThat(found.getTitle()).isEqualTo("Write the design doc");
        assertThat(found.getDescription()).isEqualTo("cover the API contract");
        assertThat(found.getStatus()).isEqualTo(TaskStatus.IN_PROGRESS);
        assertThat(found.getPriority()).isEqualTo(TaskPriority.HIGH);
    }

    // =====================================================================
    // 2. Listing returns strictly ascending-id order (Requirement 2.1)
    // =====================================================================

    @Test
    @DisplayName("findAllByOrderByIdAsc returns tasks in strictly ascending id order (Req 2.1)")
    void findAllByOrderByIdAscReturnsAscendingIdOrder() {
        // Save three tasks. IDENTITY generation assigns increasing ids in insertion order.
        Task first = taskRepository.save(
                newTask("First", "", TaskStatus.TODO, TaskPriority.LOW));
        Task second = taskRepository.save(
                newTask("Second", "", TaskStatus.DONE, TaskPriority.MEDIUM));
        Task third = taskRepository.save(
                newTask("Third", "", TaskStatus.IN_PROGRESS, TaskPriority.HIGH));
        taskRepository.flush();

        List<Task> ordered = taskRepository.findAllByOrderByIdAsc();

        // All three are returned...
        assertThat(ordered).hasSize(3);

        // ...and their ids come back strictly ascending. Comparing the id sequence to a sorted copy
        // of itself asserts the ordering without hard-coding the exact id values the database chose.
        List<Long> ids = ordered.stream().map(Task::getId).toList();
        assertThat(ids).isSorted();
        assertThat(ids).doesNotHaveDuplicates();
        assertThat(ids).containsExactly(first.getId(), second.getId(), third.getId());

        // Spot-check that ordering is by id, not insertion-independent: titles line up with the ids.
        assertThat(ordered.stream().map(Task::getTitle).toList())
                .containsExactly("First", "Second", "Third");
    }

    @Test
    @DisplayName("findAllByOrderByIdAsc returns an empty list when no tasks exist (Req 2.1)")
    void findAllByOrderByIdAscReturnsEmptyListWhenNoTasks() {
        // The listing query on an empty table returns an empty list, never null.
        List<Task> ordered = taskRepository.findAllByOrderByIdAsc();

        assertThat(ordered).isEmpty();
    }

    // ---------------------------------------------------------------------
    // Helper
    // ---------------------------------------------------------------------

    /** Builds a Task with the given field values (the entity has no all-args constructor). */
    private static Task newTask(String title, String description, TaskStatus status,
            TaskPriority priority) {
        Task task = new Task();
        task.setTitle(title);
        task.setDescription(description);
        task.setStatus(status);
        task.setPriority(priority);
        return task;
    }
}
