package com.devtrack.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * The single persisted domain object in DevTrack: a unit of work being tracked.
 *
 * <p>This class is a JPA <em>entity</em>. JPA (Jakarta Persistence API) maps a Java object to a
 * row in a database table, so we can save/load {@code Task} objects without writing SQL by hand.
 * On Spring Boot 3 the annotations live in the {@code jakarta.persistence} package (they used to be
 * {@code javax.persistence} before the Jakarta EE rename).
 *
 * <ul>
 *   <li>{@code @Entity} tells JPA this class is persistable.</li>
 *   <li>{@code @Table(name = "tasks")} maps it to the {@code tasks} table (rather than the default
 *       {@code task}).</li>
 * </ul>
 *
 * <p>Field constraints come from Requirement 1 and the Glossary.
 */
@Entity
@Table(name = "tasks")
public class Task {

    /**
     * Primary key, generated by the database.
     *
     * <p>{@code GenerationType.IDENTITY} lets MySQL assign the id via its {@code AUTO_INCREMENT}
     * column. Letting the database own id generation gives us unique, monotonically increasing ids
     * without any application-side coordination, which also produces the ascending-id ordering the
     * listing endpoint relies on. The id is {@code null} until the row is first saved.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Required title, 1-150 characters (the trim rule is enforced in the service layer). */
    @Column(nullable = false, length = 150)
    private String title;

    /**
     * Optional free-text description.
     *
     * <p>The column is {@code NOT NULL}; when a request omits the description the service stores an
     * empty string. Initializing the field to {@code ""} here keeps a freshly constructed entity
     * consistent with that rule (Requirement 1.4).
     */
    @Column(nullable = false, length = 2000)
    private String description = "";

    /**
     * Current status, defaulting to {@code TODO} (Requirement 1.2).
     *
     * <p>{@code @Enumerated(EnumType.STRING)} stores the enum by <em>name</em> ("TODO", "DONE")
     * instead of its ordinal position (0, 1, 2). Ordinals are fragile: reordering the enum constants
     * later would silently change the meaning of existing rows. Storing the name keeps the data
     * readable and reorder-safe. {@code length = 20} sizes the {@code VARCHAR} column comfortably.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private TaskStatus status = TaskStatus.TODO;

    /** Priority, defaulting to {@code MEDIUM} (Requirement 1.3); stored by name, same as status. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private TaskPriority priority = TaskPriority.MEDIUM;

    /**
     * No-argument constructor required by JPA.
     *
     * <p>JPA instantiates entities reflectively when reading rows from the database, so every entity
     * must expose a no-arg constructor. The field initializers above still run, so a new instance
     * starts with sensible defaults.
     */
    public Task() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public TaskStatus getStatus() {
        return status;
    }

    public void setStatus(TaskStatus status) {
        this.status = status;
    }

    public TaskPriority getPriority() {
        return priority;
    }

    public void setPriority(TaskPriority priority) {
        this.priority = priority;
    }
}
